### PR TITLE
Ed customers

### LINKED ISSUE #11: Display Customers that haven't placed an Order
By using the URL parameter `/customers/?active=false`, the JSON response should only contain customers that don't have any orders placed yet.

### PR DESCRIPTION
**Pull request by CurtainUp**
## Link to Ticket
Closes #11

## Description of Proposed Changes
By using the URL parameter /customers/?active=false, the JSON response should only contain customers that don't have any orders placed yet.

## Steps to Test

```sh
git fetch --all
git checkout ed-customers
```
python manage.py runserver
/customers/?active=false

## Impacted Areas in Application
Customers

## Mentions @username
@johnnathanwood 
@danielreedcombs 
@buffard

### CODE REVIEW

**Comment by danielreedcombs** [comment]
👍

**Comment by CurtainUp** [comment]
Updated so customer/ should show all customers regardless of active bool

**Review by buffard — APPROVED** [review]
👍

**Comment by johnnathanwood** [comment]
sick

**Pull request merged**
